return {
    mod_name = { en = "Practice Minigames" },
    mod_description = { en = "Practice Darktide minigames and track completion times." },
    practice_toggle_key = { en = "Open Practice" },
    practice_toggle_key_tooltip = { en = "Open or close the practice selector. Press it during practice to return to the selector." },
    practice_selector_title = { en = "PRACTICE MINIGAMES" },
    practice_selector_subtitle = { en = "SELECT TRAINING PROGRAM" },
    practice_selector_controls = { en = "A / D, Arrows, or Stick Select   Enter / Space / Interact Start   Esc Close" },
    practice_type_decode_symbols = { en = "Decode Symbols" },
    practice_type_decode_search = { en = "Decode Search" },
    practice_type_drill = { en = "Tree Drill" },
    practice_type_frequency = { en = "Frequency Matching" },
    practice_type_balance = { en = "Train Balance" },
    practice_selector_desc_decode_symbols = { en = "Decode symbol sequences" },
    practice_selector_desc_decode_search = { en = "Match target patterns" },
    practice_selector_desc_drill = { en = "Navigate the logic tree" },
    practice_selector_desc_frequency = { en = "Align signal frequencies" },
    practice_selector_desc_balance = { en = "Stabilize the balance node" },
    practice_not_allowed = { en = "Practice can only be used in the Mourningstar or Psykanium." },
    practice_result = { en = "%s completed in %.2fs." },
}
